language: node_js

stages:
  - Test
  - name: Release
    if: commit_message !~ /(release)/

jobs:
  include:
    - stage: Test
      node_js:
        - lts/*
        - node
    - stage: Release
      node_js: "lts/*"
      install: npm install --no-package-lock
      before_deploy:
        - git config user.email "travis@travis-ci.org"
        - git config user.name "Travis CI"
        - git remote set-url origin https://${GH_TOKEN}@github.com/Kikobeats/automate-release.git
        - git pull origin master
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release
        on:
          branch: master