language: node_js
node_js:
  - "lts/*"
deploy:
  provider: script
  on: 
    branch: master
  script:
    - git config user.email "$GIT_EMAIL"
    - git config user.name "$GIT_USERNAME"
    - npm run release

  